### ISSUE TITLE
Translate from English to Swahili [2-4h]

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/tilt-game#2]
Translate https://github.com/literacyapp-org/tilt-game-android/blob/master/app/src/main/res/values-sw/strings.xml

**Comment by jo-elimu** [comment]
![screenshot_20170302-105435](https://cloud.githubusercontent.com/assets/1451036/23498553/49602b64-ff39-11e6-9a50-a99437ad2d05.png)
![screenshot_20170302-105441](https://cloud.githubusercontent.com/assets/1451036/23498555/4962b8ca-ff39-11e6-8fe4-56d90123fd5a.png)
![screenshot_20170302-105445](https://cloud.githubusercontent.com/assets/1451036/23498552/495d0646-ff39-11e6-9558-d9e66f3a82d9.png)
![screenshot_20170302-105448](https://cloud.githubusercontent.com/assets/1451036/23498556/49634df8-ff39-11e6-9b91-c5ff7be2d097.png)
![screenshot_20170302-105458](https://cloud.githubusercontent.com/assets/1451036/23498554/49602ac4-ff39-11e6-8126-fff41c4d7f6c.png)
![screenshot_20170302-105502](https://cloud.githubusercontent.com/assets/1451036/23498557/499718ea-ff39-11e6-965c-e6a9899200db.png)
![screenshot_20170302-105509](https://cloud.githubusercontent.com/assets/1451036/23498559/4997ac4c-ff39-11e6-95f4-6fd530c11cac.png)
![screenshot_20170302-105515](https://cloud.githubusercontent.com/assets/1451036/23498558/49979c84-ff39-11e6-9a8e-811838c87fed.png)
![screenshot_20170302-105520](https://cloud.githubusercontent.com/assets/1451036/23498561/49a813d4-ff39-11e6-9ce1-c572d4e75a77.png)
![screenshot_20170302-105523](https://cloud.githubusercontent.com/assets/1451036/23498560/4997f422-ff39-11e6-93af-4dbff1484884.png)
![screenshot_20170302-105554](https://cloud.githubusercontent.com/assets/1451036/23498562/49b65f34-ff39-11e6-912a-e3869b4ebc79.png)
![screenshot_20170302-105556](https://cloud.githubusercontent.com/assets/1451036/23498563/49c31ac6-ff39-11e6-9b12-e537fd7033d5.png)
![screenshot_20170302-105601](https://cloud.githubusercontent.com/assets/1451036/23498565/49c583e2-ff39-11e6-9e2c-47f30479b1ce.png)
![screenshot_20170302-105632](https://cloud.githubusercontent.com/assets/1451036/23498564/49c4e770-ff39-11e6-9f69-1a684973448d.png)
